# Generated by Django 3.2.4 on 2021-06-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('CandidateId', models.AutoField(primary_key=True, serialize=False)),
                ('CandidateName', models.CharField(max_length=100)),
                ('CandidateEmail', models.EmailField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('ScheduleId', models.AutoField(primary_key=True, serialize=False)),
                ('JoiningDate', models.DateField()),
                ('StartTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField()),
            ],
        ),
    ]
