# Generated by Django 3.2.4 on 2021-06-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0002_schedule_participantname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='EndTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='StartTime',
            field=models.TimeField(),
        ),
    ]
