# Generated by Django 3.2.4 on 2021-06-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0003_auto_20210619_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='Resume',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ParticipantName',
            field=models.CharField(max_length=100),
        ),
    ]
