# Generated by Django 3.2.4 on 2021-06-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0004_auto_20210620_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='Resume',
        ),
        migrations.AddField(
            model_name='candidates',
            name='Resume',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
